#-------------------------------
# General Site Settings
title: AGU - NASA Ethics in AI/ML
logo: agu-trademark-logo-horiz.png # You can add own logo.
description: Engage AI/ML community to develop a set of principles and responsibilities for using AI/ML in Earth and environmental science-focused research. The goal is for these principles to be endorsed and adopted by organizations and institutions and used to update or inform general Scientific Code of Conduct policies. 


#-------------------------------
# Author Settings
author:
  name: AGU - NASA Ethics in AI/ML
  image: AGU-Stock-Nasa-Earth-Satellite.jpg
  say-hello: AGU - NASA Ethics in AI/ML
  bio: Engage AI/ML community to develop a set of principles and responsibilities for using AI/ML in Earth and environmental science-focused research. The goal is for these principles to be endorsed and adopted by organizations and institutions and used to update or inform general Scientific Code of Conduct policies. 


#-------------------------------
# Contact links


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
